import { verifyDemoToken } from "@/lib/tokens";

export const dynamic = "force-dynamic";

export default async function VerifyPage({ searchParams }: { searchParams: Promise<{ token?: string | string[] }> }) {
  const { token } = await searchParams;
  const result = typeof token === "string" ? verifyDemoToken(token, process.env.DEMO_CERT_TOKEN_SECRET ?? "") : { ok: false as const, error: "No token supplied" };
  return <main className="min-h-screen bg-[#f3f7f9] px-5 py-14"><div className="mx-auto max-w-xl rounded-2xl border border-[#d4e1e8] bg-white p-7 shadow-panel sm:p-10"><div className="text-xs font-bold uppercase tracking-[.18em] text-[#1684ab]">Kee Safety · KeeTrack</div><h1 className="mt-5 text-3xl font-black tracking-[-.05em] text-[#0b3151]">Demo certificate verification</h1>{result.ok ? <><div className={`mt-7 rounded-xl border p-5 ${result.snapshot.status === "Valid" ? "border-[#bde1ca] bg-[#effaf3]" : "border-[#f0c2c3] bg-[#fff5f5]"}`}><div className="text-xs font-bold uppercase tracking-[.14em] text-[#0b3151]">{result.snapshot.status}</div><div className="mt-2 text-2xl font-bold text-[#0b3151]">{result.snapshot.certificateNo}</div><p className="mt-2 text-sm text-slate-600">{result.snapshot.assetRef} · {result.snapshot.assetType}</p></div><dl className="mt-7 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase tracking-[.1em] text-slate-500">Issued</dt><dd className="mt-1 font-semibold text-[#0b3151]">{result.snapshot.issuedDate}</dd></div><div><dt className="text-xs font-bold uppercase tracking-[.1em] text-slate-500">Expires</dt><dd className="mt-1 font-semibold text-[#0b3151]">{result.snapshot.expiryDate}</dd></div></dl><p className="mt-8 border-t border-[#e1e9ee] pt-4 text-xs leading-relaxed text-slate-500">Demo certificate / status as of {result.snapshot.asOf}. This page displays an immutable signed snapshot and is not live certification.</p></> : <div className="mt-7 rounded-xl border border-[#f0c2c3] bg-[#fff5f5] p-5 text-sm text-[#a52e35]">{result.error}</div>}</div></main>;
}
